### ISSUE TITLE
How to accelerate Kinectv2 using Jetson TX2?

### ISSUE THREAD

**Issue by wuhanmoon** [jetsonhacks/installLibfreenect2#1]
Hi, thanks for sharing. Here are some questions:
1. Does the board Jetson TX2 support the OPENCL? 
2. When running the Libfreenect2/build/bin/Protonect, I noticed that "Environment variable LIBFREENECT2_PIPELINE can be set to cl, cuda, etc to specify the pipeline". 
And when running the kinect2_bridge on ROS,  the "depth_method" could be chosen among "cpu, opencl, opengl, cuda...", but the "reg_method" could be only set to "cpu ". When "reg_method" set to "opencl", the problem "OpenCL registration is not available!" occurred. 
Also the frame rate of HD/QHD point clouds was very low.  
So, is there a way to accelerate the HD/QHD points cloud acquisition on ROS for Jetson TX2? 

Looking forward for your reply.

**Comment by jetsonhacks** [comment]
1. The Jetson TX2 does not support OpenCL
2. I don't know the answer to your second question

**Comment by wuhanmoon** [comment]
Thank you all the same!

**Comment by angelbeibei** [comment]
@wuhanmoon 
the board Jetson TX2
 rosrun  kinect2_bridge kinect2_bridge _reg_method:=cpu
[DepthRegistration::New] OpenCL registration method not available!
[DepthRegistration::New] OpenCL registration method not available!
[OpenGLContext] failed to initialize glew for the current context!
can you tell me how to do this？thank you！

**Comment by jetsonhacks** [comment]
This repository does not install the ROS bridge. 
In the usage directions for kinect2_bridge:

reg_method:=<string>
    default: opencl
    info:    Use specific depth registration: default, cpu, opencl

You wrote:

$ rosrun kinect2_bridge kinect2_bridge _reg_method:=cpu

_reg_method is not a valid parameter flag. 
The default for reg_method is OpenCL which is not supportted by the Jetson.

**Comment by angelbeibei** [comment]
@jetsonhacks 
thank you!
but i run $rosrun  kinect2_bridge kinect2_bridge reg_method:=cpu 
Report the error：[DepthRegistration::New] OpenCL registration method not available! 
so What should I do to change to cpu registration method?

**Comment by jetsonhacks** [comment]
I would think that you should ask on the kinect2_bridge repository.
