### ISSUE TITLE
ubuntu. any steps on how to install this for ubuntu?

### ISSUE THREAD

**Issue by dackdel** [jetsonhacks/installLibfreenect2#3]

**Comment by JetsonHacksNano** [comment]
I don't understand the question. Are you asking how to install this on a PC or a NVIDIA Jetson?

**Comment by dackdel** [comment]
How to install on a pc that is running ubuntu.

**Comment by jetsonhacks** [comment]
Please see the Intel librealsense 2 library on Github: https://github.com/IntelRealSense/librealsense for installation instructions for Ubuntu on a PC.
